pipelines:
  default:
    - step:
        name: Build and test
        image: node:12.8.0
        caches:
          - node
        script:
          - yarn
          - yarn build
          - yarn lint
          # - yarn test
        artifacts:
          - build/**
          - storage/**
          - node_modules/**
    - step:
        name: Deploy
        deployment: staging
        image: bitbucketpipelines/rsync-deploy:0.3.2
        script:
          - ssh deploy@82.102.2.5 \~/export_db.sh aai staging
          - rsync -azr --progress build node_modules storage deploy@82.102.2.5:\~/applications/aai/staging --exclude="storage/db.sqlite"
          - ssh deploy@82.102.2.5 pm2 restart aai.staging && pm2 restart ssme
